// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
Insert into feed_follows (id,id_feed,id_user,created_at,updated_at)
Values($1,$2,$3,$4,$5)
RETURNING id, id_user, id_feed, created_at, updated_at
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	IDFeed    uuid.UUID
	IDUser    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.IDFeed,
		arg.IDUser,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.IDUser,
		&i.IDFeed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
